services:
  web:
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    networks:
      - my-net
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/config:/etc/prometheus
      - ./prometheus/data:/prometheus
    networks:
      - my-net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana/data:/var/lib/grafana
    networks:
      - my-net

networks:
  my-net:
    driver: bridge